# -*- coding: utf-8 -*-
"""SD 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vA2xPHNZtpFv8VsBRHeLWDWCSJku44J-
"""

# latihan 1
data = []
NPM = [2420506032, 2420506033, 2420506034, 2420506035, 2420506036]
print("isi array NPM", NPM)